name: badge-ci

on: [push, pull_request, workflow_dispatch]

jobs:
  build-project:
    runs-on: ubuntu-latest

    strategy:
     matrix:
       java-version: [ 19 ]

    steps:
      - name: Checkout source repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up JDK ${{ matrix.java-version }}
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java-version }}

      - name: Grant execute permission
        run: chmod +x bld.sh

      - name: Run tests
        run: ./bld.sh download compile test -DtestsBadgeApiKey=${{ secrets.TESTS_BADGE_API_KEY }}