name: bld-ci

on: [push, pull_request, workflow_dispatch]

jobs:
  build-project:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 17

      - name: Run tests
        run: >-
          ./bld download compile test
          -DtestsBadgeUrl=https://rife2.com/tests-badge/update/com.uwyn/tests-badge
          -DtestsBadgeApiKey=${{ secrets.TESTS_BADGE_API_KEY }}